apiVersion: v1
data:
  password: REDACTED
  username: REDACTED
kind: Secret
metadata:
  name: mongo-creds
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemz-db
  labels:
    app: gemz
    deployment: gemz-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemz
      deployment: gemz-db
  template:
    metadata:
      labels:
        app: gemz
        deployment: gemz-db
    spec:
      containers:
        - name: database
          image: mongo
          resources:
            limits:
              cpu: 500m
              memory: 1G
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
          volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "pvc"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gemz
  name: gemz-db-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: gemz
    deployment: gemz-db